### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by nkawano1221** [nkawano1221/chat-space#11]
#18.182.242.81

**Comment by kohei-isoda** [comment]
川野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯ 一定時間が経つとそのグループのメッセージが全て自動更新で出力されてしまう

◯ メッセージの上部・下部の間に大きな余白が生まれてしまっている
[![Screenshot from Gyazo](https://gyazo.com/e6defb83ed6a6792c4bfa70e9af7fe49/raw)](https://gyazo.com/e6defb83ed6a6792c4bfa70e9af7fe49)

◯ フラッシュメッセージが出現すると下部のフォームが埋まってしまう
[![Screenshot from Gyazo](https://gyazo.com/b90dc6608f6d622ef9a0d2d8e9dd9744/raw)](https://gyazo.com/b90dc6608f6d622ef9a0d2d8e9dd9744)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by nkawano1221** [comment]
修正いたしました！よろしくおねがいいたします。

**Comment by yasunamiura** [comment]
川野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、前回分の修正は確認できました。

また以下の不備が見受けられましたので修正をお願いします！
- リロードするとメッセージにCSSが当たっていない
[![Image from Gyazo](https://i.gyazo.com/bd3aca324d7536008344bd6958babc84.png)](https://gyazo.com/bd3aca324d7536008344bd6958babc84)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by nkawano1221** [comment]
再度、修正いたしました。お手数をおかけしますが、よろしくお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**①Edit Accountの文字色が見本と異なる（サインイン、ログインも同様です）**
[![Image from Gyazo](https://i.gyazo.com/02357c23ca3ebafa53313f7a4066eda5.png)](https://gyazo.com/02357c23ca3ebafa53313f7a4066eda5)

※カリキュラムの中にある、模範のchatspaceと仕様書を参考に、修正をお願いします。
[模範のchatpsace]
https://chat-space-sample.herokuapp.com/
[仕様書]
https://tech-master.s3.amazonaws.com/uploads/curriculums//03e925297f3843c603f028b177b4e86b.png

修正完了次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by nkawano1221** [comment]
文字色修正いたしました！お手数をおかけしますが、ご確認お願いします！

**Comment by naru6117** [comment]
早速のご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
最終課題もがんばってください！！
